package com.csq.thesceneryalong.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.csq.thesceneryalong.db.Track;
import com.csq.thesceneryalong.db.TrackPoint;
import com.csq.thesceneryalong.db.Scenery;

import com.csq.thesceneryalong.db.TrackDao;
import com.csq.thesceneryalong.db.TrackPointDao;
import com.csq.thesceneryalong.db.SceneryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig trackDaoConfig;
    private final DaoConfig trackPointDaoConfig;
    private final DaoConfig sceneryDaoConfig;

    private final TrackDao trackDao;
    private final TrackPointDao trackPointDao;
    private final SceneryDao sceneryDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        trackDaoConfig = daoConfigMap.get(TrackDao.class).clone();
        trackDaoConfig.initIdentityScope(type);

        trackPointDaoConfig = daoConfigMap.get(TrackPointDao.class).clone();
        trackPointDaoConfig.initIdentityScope(type);

        sceneryDaoConfig = daoConfigMap.get(SceneryDao.class).clone();
        sceneryDaoConfig.initIdentityScope(type);

        trackDao = new TrackDao(trackDaoConfig, this);
        trackPointDao = new TrackPointDao(trackPointDaoConfig, this);
        sceneryDao = new SceneryDao(sceneryDaoConfig, this);

        registerDao(Track.class, trackDao);
        registerDao(TrackPoint.class, trackPointDao);
        registerDao(Scenery.class, sceneryDao);
    }
    
    public void clear() {
        trackDaoConfig.getIdentityScope().clear();
        trackPointDaoConfig.getIdentityScope().clear();
        sceneryDaoConfig.getIdentityScope().clear();
    }

    public TrackDao getTrackDao() {
        return trackDao;
    }

    public TrackPointDao getTrackPointDao() {
        return trackPointDao;
    }

    public SceneryDao getSceneryDao() {
        return sceneryDao;
    }

}
